name: mfema_chat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ionicons: ^0.2.2

  flutter_gen: ^5.4.0
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  cookie_jar: ^4.0.8
  http_client: ^1.5.3
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
